---
title: "Coral Monitoring with Sentinel_2"
author: "Joachim Muench"
date: "2023-07-27"
output: word_document
categories: []
tags: []
editor_options:
  markdown:
    wrap: sentence
slug: "coral-monitoring-with-sentinel-2"
---

Philipps-Universität-Marburg Masterstudiengang Physische Geographie Seminar „Geographische Informationssysteme"

Exposé zur Projektarbeit „Monitoring von Korallenriffen basierend auf Sentinel Daten"

vorgelegt von Joachim Werner Münch aus Lohra (Hessen)

Einleitung 
Korallenriffe gelten als Hot Spots mit extrem hoher Biodiversität und als Reservate für unzählige seltene Arten und Lebensgemeinschaften. Vor diesem Hintergrund sind sie besonders sensibel für Klima- und Umweltveränderungen. Trotz umfangreicher nationaler und internationaler Schutzmaßnahmen ist gerade bei den größten und mächtigsten Riffen wie dem Great Barrier Reaf vor der Nordostküste Australiens ein Rückgang festgestellt worden, dessen Ursachen aber noch nicht bis in alle Einzelheiten erfasst werden konnten. Ein Teil davon ist aber sicherlich auf Korallenbeiche zurückzuführen, die in den letzten Jahrzehnten immer mehr zugenommen hat (Anthony 2016, Dubinsky und Stambler 1996, Eddy et al. 2021, Hoegh-Guldberg et al. 2007), so dass eine Regeneration in immer mehr Fällen nicht möglich war und ist. 
Bereits seit den 1970er Jahren versucht man die Riffe auch mit Fernerkundungsdaten zu erfassen, um Veränderung in Riffgröße und Zusammensetzungen zu fixieren und mit allgemeinen Umweltdaten in Zusammenhang zu bringen. Im Jahre 1979 wurde erstmals in Australien eine Empfangsstation für LANDSAT eingerichtet, von der aus Aufnahmen des Great Barrier Reefs genommen und diese mit Orthofotos verglichen wurden (Hopley et al. 2007, 139). Vor allem für groß angelegte Korallenstudien werden Spektralbilder ausgehend von Satelliten eingesetzt. (Bajjouk et al. 2019, Bertels et. al 2008) Dabei versucht man über Riff- und Wasseroberflächentemperatur die Bleichereignisse einzuordnen und das Risiko von Bleichereignissen einzuschätzen. (Weeks et al. 2013)  In den letzten Jahren konnte man dafür verstärkt auf hochauflösende, in regelmäßigen Zeitabständen vorhandene Sentinel Daten zurückgreifen. Da das räumliche und zeitliche Netz verfügbarer Klimadaten immer enger geworden ist, bieten sich auf künstlicher Intelligenz basierende Methoden zur Feststellung von Korrelationen von Riffwachstum bzw. Zerstörung durch massive Zunahme an Korallenbleiche an, die eine Regeneration in der Folgezeit unmöglich werden lässt.
Die Korallenbleiche entsteht, wenn länger anhaltend hohe Temperaturen die Algen, die sich im Korallengewebe befinden und die Koralle in symbiotischer Beziehung mit wichtigen Mikronährstoffen versorgen, zum Verlassen ihres Lebensraums drängen.(Lesser 2011) Die Algen übernehmen zahlreiche lebenswischtige Funktionen für die Koralle ein, von der Stabilisierung des Riffgerüsts über die Produktion tropischer Sande und die Nährstoffspeicherung bis hin zur Regelung der Trophie (Fong und Paul 2011). Bei längerem Fehlen dieser Nährstoffquelle stirbt anschließend auch die Koralle selbst ab. Das Verlassen der Algen geschieht vor allem, wenn die Meeresoberflächentemperatur den Toleranzbereich der Korallenkolonie für einen längeren Zeitraum von mehreren Tagen oder sogar Wochen übersteigt. Diese Situation kann schon eintreffen, wenn die Sommertemperaturen nur um 1-2°C über dem bisherigen Durchschnittswert liegen (Liu und Strong 2003).
Diskutiert wird dabei vor allem, inwieweit durch den Klimawandel hervorgerufene, langanhaltende sommerliche Hitzeperioden mit geringem Stoffaustausch, sowohl in der Luft als auch im Wasser, diese Korallenbleiche qualitativ und quantitativ so stark begünstigen, dass eine Regeneration in der Zwischenzeit nicht mehr möglich ist.
Um hierfür brauchbare Vorhersagen treffen zu können, die nicht nur für einzelne Korallen, sondern für große Riffgebiete wie das in der Nordsüdausdehnung über 2300 km mächtige Great Barrier Reef oder gar im globalen Maßstab gültig sind, braucht es durchgängig verfügbare Aufnahmedaten, die zugleich eine Auflösung besitzen, die sich für die großflächige Markierung von Korallenbleiche und ihre berechnete und modellhaft vorhergesagte Zu- bzw. Abnahme eignet. 
In der Vergangenheit sind Korallenriffe im Wesentlichen mittels Orthofotos von Flugzeugen und Meerestauchern untersucht worden. Um die Jahrtausendwende kamen LIDAR - Daten und Aufnahmen von LANDSAT hinzu, die jedoch immer nur in mehrjährigen Zeitabständen verfügbar sind.
Mittels Sentinel Satelliten verfügt das Satellitenprogramm der europäischen Raumfahrbehörde ESA seit vergangenem Jahrzehnt  über regelmäßige Aufnahmen vom gesamten Globus, wobei vor allem Sentinel 2 A (seit 2015) und 2 B (seit 2017) Bilder relativ kleiner Erdabschnitte in hoher Auflösung garantieren, mit denen es prinzipiell möglich erscheint, gebleichte Korallenabschnitte von gesunden Korallenabschnitten zu unterscheiden. So ist es im Februar 2017 beispielsweise zu einer großflächigen Bleiche der Riffe vor der australischen Küste gekommen, die mit Sentinel 2a Daten umfangreich dokumentiert werden konnte (Hedley et al. 2018).
Wenn diese wahrgenommenen Veränderungen sich anhand weniger markierter Befunde in ihrem Gesamtausmaß sowohl räumlich als auch zeitlich errechnen und modellhaft vorhersagen ließen, hätte man ein geeignetes Werkzeug, um ein kostengünstiges Korallen-Monitoring durchzuführen und in Abhängigkeit von Umwelt- und Klimaparametern überzeugende Vorhersagen zu treffen.
- Lässt sich aus einer begrenzten Zahl an markierten Bleichabschnitten das Gesamtausmaß eines regionalen Bleichereignisses einigermaßen exakt erfassen?
- Lässt sich die zeitliche Dauer und Intensität der Bleichen so weit vorhersagen, dass bei Kenntnis der regionalen Umweltbedingungen der Anteil an Regeneration bzw. totaler Zerstörung in Abhängigkeit von der Zeit ebenfalls vorhergesagt werden kann?
- Eignen sich Sentinel-2 Aufnahmen als Grundlage für ein langfristig und großräumig angelegtes Riffmonitoring?
Da bereits in den ersten Jahren der Sentinel-2 Datenverfügbarkeit Bleichereignisse an einzelnen Korallen ziemlich exakt in räumlicher und zeitlicher Ausdehnung erfasst wurden, besteht die Zuversicht, dies modellhaft auch für größere Riffabschnitte so exakt errechnen und vorhersagen zu können, um sich die Untersuchung von Einzelkorallen über Orthofotos, LIDAR-Aufnahmen oder gar Taucherproben mit Laboranalysen zu ersparen. Die fehlende exakte Kenntnis der Regenerationsfähigkeit unterschiedlicher Korallenarten dürften derartige Untersuchungen mittelfristig jedoch noch nicht vollständig ersetzen können.

Untersuchungsgebiet
Als Untersuchungsgebiet ist ein Ausschnitt aus dem südlichen Abschnitt des Great Barrier Reef nördlich der K´gari Insel und westlich der Küstenstädte Gladstone und Mackay im Süden des australischen Bundesstaats Queensland ausgewählt worden. Von diesem Riffabschnitt waren Sentinel-2 Aufnahmen verschiedener Aufnahmejahre seit dem Start von Sentinel-2 zeitnah online verfügbar und konnten demzufolge im Hinblick auf gebleichte Korallenabschnitte miteinander verglichen werden. Abbildung 1 zeigt den gesamten analysierten Abschnitt auf drei Echtfarbenbildern vom 27. Oktober 2017. Nach dem European Petroleum Survey Group Geodesy (EPSG) befindet sich das Gebiet im Bereich 32756 im World Geodetic System 1984 (WSG 84) in der UTM Zone 56S. Dabei liegen die Rechtswerte zwischen 30000 und 40000 und die Hochwerte zwischen 7350000 und 7500000. Umgerechnet ergibt sich damit ein Koordinatenbereich zwischen 20,4° und 23,2° südliche Breite sowie 152,1° und 153,8° östliche Länge. 

Methodik 
Zuerst wurden die Sentinel 2 Aufnahmen mit QGIS von jp2- in ein tif- Format umgewandelt. Außerdem wurde eine shape Datei mit Trainingsdaten erstellt, bestehend aus ausgewählten Polygonen, die gespeichert als verschiedene Klassen, markiert wurden. Dabei wurden die Polygone vier verschiedenen Klassen zugeordnet, Koralle (bestehend aus nicht erkennbar gebleichten Korallenabschnitten), gebleichte Koralle, Meerwasser und Wolken.
Aus dem gleichen Riffabschnitt, in dem im südlich Teil sich die Trainingsdaten und im nörlichen Teil die Testdaten befinden, wurde mit dem R Paket „raster" ein Rasterdatensatz erstellt und aus diesen Vektordaten Masken gebildet. Dabei wurde eine Teilmenge der Gesamtaufnahme herausgegriffen und hiervon ein Rasterbild sowie gleichzeitig eine gerasterte Maske erzeugt. Abbildungen 2 bis 5 (a und b) lassen erkennen, dass die Masken jeweils einen Grundriss dieses Bildes darstellen. Wenngleich man durchaus Unterschiede zum Originalbild feststellt, lässt sich hiermit erahnen, welche Bereiche den einzelnen Klassen zugeordnet werden können. 
Mit Hilfe neuronaler Netze (U-Net) galt es nun, ein Modell zu trainieren, um gesunde und gebleichte Korallen, zur Gegenüberstellung aber auch reines Meerwasser und Wolkenbedeckung, in einem größeren Testgebiet bzw. in Aufnahmen eines divergenten Zeitpunktes vorherzusagen. Dabei wird das Gesamtbild geclustert und die einzelnen Segmente werden klassifiziert. Faltungsneuronale Netze (Convolutional Neural Network, kurz CNN) stellen die häufigsten neuronalen Netzwerke für die visuelle Analyse im Deep Learning dar (Valueva et al. 2020) und sollten auch bei der Vorhersage von Korallenbleiche Anwendung finden.
Diese Testdaten dienen der Vergewisserung, dass das Modell nicht nur die Korallen, sondern auch ihre gebleichten Stellen möglichst exakt in ihrer räumlichen Ausdehnung vorhersagen kann. Anschließend wurde anhand der Testdaten getestet, in wie weit das Modell in der Lage ist, Veränderungen in der Korallenausdehnung eines gegebenen Riffausschnittes zwischen den Aufnahmen aus mindestens zwei unterschiedlichen Zeitpunkten festzustellen und aus den wahrgenommenen Veränderungen, Tendenzen abzulesen, die auch Vorhersagen in die nähere Zukunft ermöglichen. 
Um die Bleiche in ihrer quantitativen Dimension aufzuzeigen und zugleich die Lokalitäten zu fixieren, wurde mit QGIS eine Change Detection durchgeführt. Hierzu wurde auf das Semi Classification Plugin (kurz: SCP)(Congedo 2021) zurückgegriffen, indem Aufnahmen des gleichen Gebietes unterschiedlicher Zeitpunkte gegenübergestellt wurden. Aufbauend auf jeweils 10 Polygonen sicher erkannter gebleichter und ungebleichter Korallen wurden Supervised Classifications durchgeführt, wobei der Unterscheidbarkeit halber reines Meerwasser und Wolkenbedeckung erneut als zwei weitere Klassen mit zugehörigen Polygonen gesetzt wurden. Die beiden klassifizierten Aufnahmen wurden anschließend miteinander in Form einer Land-Cover-Change gegenübergestellt. Anhand der Pixelanzahl sollte zum einen das relative Ausmaß der Bleiche in dem Untersuchungsabschnitt im entsprechenden Zeitintervall vorhergesagt und zum andern nach Pixelmenge und dementsprechend Fläche quantifiziert werden. Wichtig für ein aussagekräftiges Ergebnis erweist sich, exakt die gleichen Klassen mit möglichst der gleichen Anzahl an Polygonen zu verwenden. Um ein weitgehend sicheres Ergebnis zu erhalten, sollten die Aufnahmen von allen, in Sentinel- 2 eingesetzten Bändern (1-12 und 8a) außer dem Echtfarbild (True Clour Image) einbezogen werden. 
Da bei neueren Aufnahmen aus den Jahren 2022 und 2023 die Aufnahmen in 10 Metern, 20 Metern und 60 Metern Auflösung vielfach in getrennten Ordnern  existieren, bietet sich hier die Change Detection für jede der drei Auflösungsstärken einzeln an. Doch auch hierbei ist es wesentlich, für beide miteinander zu vergleichenden Zeitpunkte die gleichen Bänder zu verwenden. Zudem sollten möglichst Aufnahmen verwendet werden, auf denen unmittelbar über den Korallen Wolkenfreiheit herrscht, so dass die Korallen in ihrer vollständigen Ausdehnung in den Aufnahmen zu erkennen sind. Weiterhin empfiehlt es sich, die über Teilen der Meeresumgebung vorhandenen Wolken, die gewöhnlich ebenfalls deutlich heller erscheinen als das Meerwasser, als eigene Klasse einzugeben, um Missinterpretationen zu den gebleichten Korallenabschnitten zu vermeiden. Um die Ergebnisse im Hinblick auf die Regenerationsfähigkeit der gebleichten Korallen angemessen zu interpretieren, wurde eine Change Detection sowohl für ein relativ kurzes Zeitintervall aus zwei verschiedenen Jahreszeiten innerhalb desselben Jahres als auch für etwas längere Intervalle (mehrere Jahre) durchgeführt. 
Ein überdurchschnittlich heißer Sommer, der großflächige Bleiche verursacht, muss schließlich nicht zwangsläufig eine nachhaltige Störung eingergehend mit Absterben der betroffenen Korallen bedeuten. Die Widerstandsfähigkeit dürfte vielmehr von der Häufigkeit dieser Bleichereignisse einerseits und der Wiederbesiedlungsgeschwindigkeit der bei der Bleiche verschwundenen, in Symbiose mit den Korallen lebenden Algen andererseits abhängen. Um zu testen, ob und wie stark einem Bleichereignis Regeneration gefolgt ist, empfiehlt es sich, vor allem Spätsommeraufnahmen und Spätherbst- bzw. Winteraufnahmen (auf der Südhemisphäre von Ende März oder Anfang April sowie von Juni oder Juli) miteinander zu vergleichen, was hier nur für das Jahr 2022 durchgeführt wurde, von dem ausreichend Daten zeitnah zu bekommen waren. Ältere Aufnahmen existieren zwar auch, waren aber nicht in so großer Zahl zeitnah online verfügbar. Zudem waren für 2022 sowohl Spätsommer- als auch Winteraufnahmen in allen drei Auflösungsstärken (10 Meter, 20 Meter und 60 Meter) in den jeweils gleichen Kanälen verfügbar, womit sich auch eine Gegenüberstellung aller drei Aufläsungsstärken durchführen ließ. Die Change detection für ein größeres Intervall von mehreren Jahren sollte dazu dienen, das längerfristige Verhältnis zwischen neuer Bleiche und Regeneration zu analysieren. 
Die Change Detection wurde auf folgende Weise durchgeführt. Zuerst wurden von der älteren Aufnahme alle verfügbaren Kanäle ausgewählt und davon ein virtueller Rasterlayer erstellt. Daraufhin wurden für jede Klasse je 10 Polygone markiert, mit denen eine Supervized Classification durchgeführt wurde, welche anschließend im gleichen Ordner abgespeichert wurde. Das gleiche Verfahren wurde daraufhin mit der jüngeren Aufnahme wiederholt. Abschließend galt es, die beiden erstellten Tif-Dateien in einer sogenannten Land-Cover-Change gegenüberzustellen, wobei die ältere Aufnahme den Referenz-Layer und die jüngere den neuen Layer darstellt. Das Programm rechnete nun für beide Aufnahmen die Anzahl der Pixel aus, die der Vorhersage nach jeder Klasse zugeordnet werden und erhält so die Pixelanzahl, die in einer Klasse geblieben oder in eine andere Klasse gewechselt sind. In Kenntnis des Georeferenzsystems wurde hierfür zugleich die jeweilige zugehörige Fläche in m² angegeben. 
Die Zuordnung zu einer Klasse kann übrigens nach drei verschiedenen Methoden vorgenommen werden, der Minimumdistanz, der maximalen Ähnlichkeit und der Spektralwinkelkartierung. Da die Bleichung im Wesentlichen an den Außenrändern der Korallen stattfindet und im Verhältnis zu den anderen drei Klassen einen relativ kleinen Bereich abdeckt, waren die Polygone für die gebleichten Korallen in den meisten Fällen so klein, dass die maximale Ähnlichkeit hiermit nicht erfolgversprechend durchgeführt werden konnte. Auch mittels Spektralwinkelkartierung ließ sich für die vier ausgewählten Klassen keine handhabbare Klassifikation durchführen. Deswegen musste sich diese Untersuchung auf die Minimumdistanz als Unterscheidungsmaß beschränken, was aber nicht bedeutet, dass bei anderen Aufnahmen nicht auch die anderen Klassifikationsmethoden Anwendung finden können. 
Neben der Pixelanzahl und der Fläche, die in dem gewählten Zeitabschnitt in eine andere Klasse gewechselt oder in der gleichen Klasse geblieben ist, und in einer vom Programm erstellten CSV-Datei angezeigt wird, lässt sich die Änderung anschließend durch Einfärbung der neu erstellten Tif-Datei auch kartographisch markieren. 
Problematisch für die Aussagekraft einer Change Detection basierend ausschließlich auf Sentinel-2 Aufnahmen könnte sich allerdings die Tatsache erweisen, dass diese erst seit wenigen Jahren vorhanden sind. Man kann daher auch nur relativ kurze Zeitabschnitte miteinander vergleichen, die nicht unbedingt im Hinblick auf langfristige Vorhersagen, die den Klimawandel angemessen mit einbeziehen, aussagekräftig sind. Für ein längerfristiges, im Hinblick auf Zukunftsprognosen taugliches Korallenmonitoring, das mit Umwelt- und Klimaveränderungen globaler und regionaler Ausmaße in einem gemischten Modell in Zusammenhang gebracht werden kann, wären zusätzlich Daten aus älteren Zeiträumen zum Abgleich hilfreich, die - wenn überhaupt - nur von Landsat oder LIDAR mit großen Zwischenintervallen vorhanden sind. Die Aufnahmen verschiedener Satelliten lassen sich in einer SCP Land-Cover-Change allerding nicht miteinander vergleichen, da jeweils andere Bänder in anderen Wellenlängenbereichen eingesetzt werden. Vor diesem Hintergrund sollten auch gemischte Modelle auf Sentinelbasis, die z.B. Klimavorhersagen einbeziehen, noch auf ihre Aussagekraft auf längere Zeitreihen hinterfragt werden. Außerdem werden den Korallen Anpassungsfähigkeiten an Klimaveränderungen nachgesagt, die aber in wenigen Jahren mit Extremereignissen noch nicht zum Tragen kommen dürften. Ein großes festgestelltes Bleichereignis in einem extrem heißen Sommer muss infolgedessen noch keineswegs bedeuten, dass zunehmende Häufigkeit dieser Extremhitzeperioden in gleichem Maße Zunahme der Bleiche und damit einhergehend eine nicht wiederherstellbare Zerstörung der Korallenriffe mit sich bringen. Vor diesem Hintergrund konnte nur getestet werden, in wie weit die Veränderungen durch die Bleichereignisse sich anhand von Sentinel-2 Aufnahmen insgesamt vorhersagen lassen, bzw. zu welchem Zeitpunkt die Zerstörung oder Schädigung durch Bleiche die größte Wirkung entfaltet.

Daten
Für die Trainings- und Testdaten wurden Spektralbilder des europäischen Satelliten Sentinel-2 (A oder B) aus den Jahren 2017, 2018 und 2022 über den Copernicus Open Access Hub angefordert. Dabei handelte es sich um atmosphärisch korrigierte Oberflächenreflexionsbilder, die von zugehörigen Level-1C-Produkten abgeleitet worden sind. Diese Level-2-Produkte bestehen aus 110x110 km² in kartographischer Geometrie (EPSG 32756, UTM25S-WGS84-Projektion).
In der einen Change Detection wurden zwei Frühlingsaufnahmen, nämlich von Oktober 2017 und November 2018, miteinander abgeglichen. Die zweite Change Detection beinhaltete einen Vergleich von Daten aus dem Frühling (Oktober) 2017 mit Winterdaten aus dem Juli 2022. Testhalber sind auch die Aufnahmen von November 2018 noch einmal mit jenen von Juli 2022 abgeglichen worden. In der vierten Change Detection sind beides Aufnahmen des Jahres 2022 gegenübergestellt worden. Sie stammten von Ende März und Mitte Juni  und somit aus dem Spätsommer und Spätherbst des entsprechenden Jahres.
Da diese beiden Aufnahmen nach unterschiedlicher Auflösung getrennte Bilder enthalten, sind alle drei Auflösungsstärken, 10 Meter, 20 Meter und 60 Meter, miteinander verglichen worden.




Ergebnisse

Aufbauend auf den in QGIS erstellten Polygonen konnten mit dem Raster Paket in R Masken erstellt werden, die sich mittels neuronaler Netzwerke trainieren ließen, welche für den gesamten Riffabschnitt Vorhersagen erlaubten. Hierbei ließ sich nicht nur vorhersagen, an welchen Stellen sich die Korallen befinden, sondern großteils auch, an welchen Stellen Bleiche an ihnen stattgefunden hatte. (siehe Abbildungen 14 und 15) Somit konnte mosaikartig ein einigermaßen genau vorhergesagtes Bild für den gesamten untersuchten Riffausschnitt für die Situation in 2017, 2018 und 2022 erstellt werden, worin Lage und Vitalität der Korallen zu den verschiedenen Zeitpunkten einigermaßen zum Ausdruck kommt. (Abbildungen 10 bis 13)
Die errechnete Genauigkeit der Trainingsdaten zeigt sich auch als sehr hoch an (siehe Abbildungen 6 bis 9), doch ist auf den als Mosaik zusammengesetzten Vorhersagebildern die Bleiche in ihrer absoluten wie relativen Ausdehnung zur Korallendichte nur schwer quantitativ abzuschätzen. Die Korallen sind zwar auf allen, als Mosaik zusammengesetzten vorhergesagten Bildern deutlich von dem sie umgebenden Meerwasser, einschließlich den von Wolken bedeckten Gebieten zu unterscheiden, die gebleichten Stellen sind jedoch vielfach kaum zu erkennen. Schaut man sich einzelne Vorhersageabschnitte an (Abbildungen 14 und 15), auf denen es mutmaßlich Bleichereignisse gegeben hatte, erscheinen diese allerdings korrekt vorhergesagt. Bei der Gegenüberstellung der Vorhersagen des gleichen Ausschnittes für verschiedene Jahre scheint zudem eine Zunahme der Bleiche mit der Zeit erkennbar. Anhand der weißen Färbung lässt sich die Bleiche auf diesem Ausschnitt allerdings nur erahnen und allenfalls im Zusammenhang mit den benachbarten Ausschnitten einigermaßen sicher feststellen. Eine Gegenüberstellung des gleichen Abschnittes von Frühling (November) 2018 und Winter (Juni) 2022 zeigt in der späteren Aufnahme dennoch eine deutlich stärker ausgedehnte Weißfärbung, die fast den gesamten Abschnitt abdeckt. Eine deutliche Zunahme der Bleiche an dieser Stelle innerhalb dieser dreieinhalb Jahre ließ sich also durchaus vorhersagen. Ob diese Vorhersage jedoch schon so ausgereift ist, dass sie sich für ein größeres Gebiet, vielleicht sogar für das ganze Great Barrier Reef zuverlässig treffen und mit konkreten Klima- und Umweltdaten im Zusammenhang bringen lässt, scheint angesichts der mangelhaften Schärfe noch zweifelhaft. Die demonstrierte, einigermaßen sichere Vorhersage belegt nichtsdestotrotz, dass die Methode der neuronalen Netzwerke für die Vorhersage von Korallenbleiche nach Sentinel-2 Aufnahmen prinzipiell geeignet ist. Sofern die gleiche Stelle regelmäßig untersucht wird, erscheint damit auch eine Entwicklung vorhersagbar, die mit Klima- und Umweltdaten auf eine Korrelation getestet und gegebenenfalls in Modelle für verschiedene Zukunftszenarios und Rückschlüsse in fernere Vergangenheit herangezogen werden kann. Sofern die errechnete Genauigkeit der Trainingsdaten außergewöhnlich hoch ausgewiesen wird, sind die gezeigten Vorhersagen zum gegenwärtigen Zeitpunkt jedoch noch großen Zweifeln zu unterziehen. 
Um die Veränderung infolge der Bleichereignisse zu quantifizieren, ist sowohl für den Zeitabschnit 2017 auf 2018, für das Intervall 2017 auf 2022, für 2018 auf 2022 als auch für März auf Juni 2022 eine Land-Cover-Change, aufbauend auf einer Supervized Classification mit dem SCP durchgeführt worden. Da hierbei neben einer Karte als Tif-Datei, die bei entsprechender Farbmarkierung die neuen bzw. nicht mehr gebleichten Stellen mit eigener Färbung darstellt sowie außerdem eine Quantifizierung nach Pixelmenge und Quadratmetern ermittelt und in einer erstellten CSV-Datei aufgelistet wird, kann man bei entsprechender Rechenkapazität auch das Gesamtausmaß an Bleiche aber auch an Regeneration für ein Gebiet vergleichbarer Bedingungen in der gegebenen Zeit quantitativ abschätzen und genauer lokalisieren, um sie mit spezifischen Umweltbedingungen wie Salzgehalt oder Wassertemperatur in Zusammenhang zu bringen.
Im Konkreten zeigte sich für den kurzen Zeitabschnitt zwischen März und Juni 2022 eine Zunahme der Bleiche, in der Form, dass erheblich mehr Pixel und Flächeneinheiten, die zu Beginn zur Klasse der gesunden Koralle gehörten, am Ende des Zeitabschnitts der Klasse der gebleichten Koralle zugewiesen wurden als umgekehrt. Dieses Ergebnis zeigte sich von der Tendenz her bei allen drei Auflösungsstärken (Tabellen 1 bis 3 und Abbildungen 16 bis 18). Erstaunlicherweise ergaben sich für den Vergleich weiter auseinanderliegender Zeitpunkte sehr unterschiedliche Ergebnisse. Die Gegenüberstellung der vorhergesagten Pixel- und Quadratmeterwerte für Oktober 2017 sowohl mit November 2018 als auch Juli 2022 zeigte deutlich mehr Anteile für Bleiche in der älteren als in der jüngeren Aufnahme, d.h. einen extremen Rückgang der Bleichen (Tabelle 4 und 5 sowie Abbildung 19 und 20). Die Gegenüberstellung der Aufnahme von November 2018 und Juli 2022 (Tabelle 6 sowie Abbildung 21) ergab hingegen das erwartete umgekehrte Ergebnis mit einerstarken relativen Zunahme der Bleiche. Entweder war die Vorhersage mindestens in einem Fall falsch - vermutlich in der ältesten Aufnahme vom Frühjahr (Oktober) 2017 - oder es ist in dieser Zeit tatsächlich zu einer starken Regeneration gekommen, die um ein Vielfaches größer war als eine neu entstandene Bleiche in einem der darauf folgenden Sommern an Korallenfläche betroffen hat. Eine dritte Möglichkeit könnte auch in einer vollständigen Überwucherung der gebleichten Stellen mit Algen in diesem längeren Zeitintervall liegen, wofür die kurze Zeitspanne vom zweieinhalb Monaten in 2022 wohl kaum ausgereicht haben dürfte. Schließlich weist das Sentinel2Coral Poject der ESA darauf hin, dass sowohl Absterben, Regenerieren als auch Überwucherung mit Algen auf dem Satellitenfoto eine Verdunklung hervorrufen, die in allen drei Fällen häufig als Rückgang der Bleiche fehlinterpretiert wird. (ESA 2017) 
Eine weitere Möglichkeit für Fehlinterpretationen könnte in einer zu hoch eingeschätzen gebleichten Fläche in den älteren Aufnahmen liegen, weil es zu Vermischungen mit Sand gekommen sein könnte. Xu et al. (2021) betonen, dass die gemischte Reflexion von Sand und dunkleren Substraten mit bloßem Auge der gebleichten Koralle sehr ähnlich sehen und die maximale Auflösung von 10 Metern bei Sentinel-2 Aufnahmen für die genaue Fixierung kleinerer Korallenflecken von wenigen Metern Umfang kaum ausreichten.
Da sich die Ergebnisse für die Change Detection so unterschiedlich zeigten, erscheint eine Korellierung der Bleiche mit speziellen Klima- und Umweltdaten in Form eines gemischten Modells, wobei vermutlich in erster Line die Dauer von sommerlichen Hitzeperioden und der Salzgehalt im umgebenden Wasser in Frage kämen, noch ein wenig spekulativ. Nichtsdestotrotz deuten vor allem die Ergebnisse der Change Detection der beiden Zeitpunkte innerhalb des Jahres 2022, die bei allen drei Auflösungsstärken von der Tendenz her gleich sind, daraufhin, dass Korallenbleiche basierend auf Sentinel-2 Aufnahmen sich durchaus quantifizieren und lokal fixieren lässt, woraus sich bei der weiteren Zunahme an Daten in absehbarer Zeit eine Basis für die großflächige Vorhersage von Bleichen in Abhängigkeit ökologischer Parameter ergibt.

Schlussfolgerung und Diskussion

Sowohl die Vorhersage basierend auf erstellten Masken von Trainingsdaten und neuronalen Netzwerken in R als auch die SCP Change Detection in QGIS nach der Minimumdistanz ermöglichen es prinzipiell, Korallenbleiche in ihrer Lokalität und raumzeitlichen Ausdehnung vorherzusagen. Im Konkreten konnte gezeigt werden, dass sich die Bleiche im südlichen Great Barrier Reef in hohem Maße auf die ozeanzugewandte Südostseite konzentriert und vor allem im Spätsommer und Herbst (d.h. in den Monaten April und Mai) auftritt. Hieraus lassen sich durchaus Konsequenzen für den Riffschutz und die ökologische Bewertung herausziehen. Allein die Tatsache, dass die Bleiche in der Gesamttendenz in den Jahren seit Beginn der Überfliegungen mit Sentinel-2 zugenommen hat, legt einen Zusammenhang mit dem Klimawandel zumindest in der untersuchten Region nahe. 
Zugleich zeigen die Ergebnisse, dass in beiden Methoden Fehlinterpretationen nicht ausgeschlossen werden dürfen. Insbesondere sollte die Interpretation von SCP Change Detection, aufbauend auf Supervized Classification bezüglich Korallenbleiche nicht leichtfertig getroffen werden. Eine mögliche Fehlerquelle könnte sich daraus ergeben haben, dass sich an den Rändern von prinzipiell gesunden Korallen Sandablagerungen befinden, die jene Stellen irrtühmlicherweise als Bleichungen anzeigen und daher die räumliche Dimension der Bleiche weit überschätzen. Außerdem erscheinen Teile aus dem Inneren der Koralle oft ähnlich hell wie die gebleichten Ränder und werden ebenfalls fälschlicherweise als Bleichungen interpretiert. Es ist zudem nicht auszuschließen, dass Bleichen an einigen Stellen bereits bei Erstellen der Trainingsdaten in ihrer Ausdehnung überschätzt wurden und somit auch anschließend bei der Vorhersage die gebleichte Fläche zu hoch eingeschätzt wird. Carter et al. (2020) weisen schließlich darauf hin, dass auf Satellitenbildern die Bleicheergnisse allgemein oft überschätzt würden. Eine solche Überschätzung ist auch bei Sentinel-2 Aufnahmen nicht auszuschließen.
Angesichts dieser zum Teil überraschenden Ergebnisse müssen auf kurze Sicht Zweifel angebracht werden, dass die Markierung von wenigen Bleichabschnitten tatsächlich das Gesamtausmaß eines Bleichereignisses und darüber hinaus das Regenerationspotential für ein so großes Gebiet wie das gesamte Great Barrier Reef erfasst. Wenngleich die Bleichabschnitte auf den vorhergesagten Mosaikbildern relativ vollständig zum Vorschein gelangten, zeigten die quantifizierten Ergebnisse der Change Detection Resultate, die auf den ersten Blick relativ unwahrscheinlich erscheinen. Es bedarf daher weiterer Untersuchungen an voneinander entfernter liegenden Riffabschnitten, um einschätzen zu können, wie plausibel diese Vorhersagen im überregionalen Maßstab tatsächlich sind. Solange die Vorhersageergebnisse selbst noch zweifelhaft erscheinen, ist auch eine Korrelation mit Umwelt- und Klimawerten im Hinblick auf regionale Zukunftsvorhersagen mit großen Unsicherheitsfaktoren versehen. Bei einer höheren Sicherheit in den Prognosen kann dies für eine begrenzte Lokalität in der Größe des hier untersuchten Gebiets dennoch ansatzweise gelingen. Die weitgehend korrekte Vorhersage des Bleichausmaßes in dem Aufnahmegebiet bei zu unterschiedlichen Zeitpunkten aufgenommenen Bildern können als hoffnungsvoller Indikator gewertet werden, auf Basis von Sentinel-2 Aufnahmen auf mittlere Sicht ein Riffmonitoring durchführen zu können, das den Rückgriff auf andere, aufwendigere und teurere Aufnahmemethoden vielerorts unnötig werden lässt. 
Letztlich bedarf es noch weiterer Change Detections in einem weitgehend bekannten abgegrenzten Gebiet, um zu derart sicheren Vorhersagen der Bleiche zu gelangen, dass für große Riffgebiete in Abhängigkeit von Umwelt- und Klimabedingungen sichere Prognosen getroffen werden können.

Literatur:

Anthony, Kenneth R.N. (2016): Coral Reefs under Climate Change and Ocean Acidification: Challenges and Oportunities for Management and Policy, in: Resour 41, 59.81.
Bajjouk, Touria; Mouquet, Pascal; Ropert, Michel; Quod, Jean-Pascal; Hoarau, Ludovic; Bigot, Lionel (2019): Detection of changes in shallow coral reefs status: towards a special approach using hyperspectral and multispectral data, in: Ecological Indicators 96, 174-191.
Bertels, L.; Vanderstraete, T.; van Coillie, S.; Knaeps, E.; Sterckx, S.; Goossens, R.; Deronde, B. (2008): Mapping of coral reefs using hyperspectral CASI data; a case study: Fordata, Tanimba, Indonesia, in: International Journal of Remote Sensing 29, 2359-2391.
Carter, Amber L.; Wilson, A. Meriwehter W.; Bello, Maximiliano; Hoyos-Padilla, E. Mairicio; Inall, Mark E.; Ketchum, James T.; Schurer, Andrew; Tudhope, Alexander W. (2020): Asessisng opportunities to support coral reef climate change refugia in MPAs: A case study at the Revillagigedo Archipelago, in: Marine Policy 112.
Congedo, Luca (2021):Semi-Automatic Classification Plugin: A Python tool for the download and processing of remote sensing images in QGIS. Journal of Open Source Software, 6(64), 3172, https://doi.org/10.21105/joss.03172
Dubinsky, Z. V.Y.; Stambler, Noga (1996): Marine pollution and coral reefs, in: Global Change Biol 2, 511-526.
Eddy, Tyler D.; Lam, Vicky W.Y.; Reygondeau, Gabriel; Cisneros-Montemayor, Andrés M.; Greer, Krista; Palomares, Maria Lourdes D. (2021): Global decline in capacy of coral reefs to provide ecosystem services, in: One Earth 4, 1278-1285.
ESA (2017): Sentinel-2 captures of coral bleaching of Great Barrier Reef, https://www.esa.int/Applications/Observing_the_Earth/Copernicus/Sentinel-2/Sentinel-2_captures_coral_bleaching_of_Great_Barrier_Reef , letzter Aufruf 20.08.2023, 15:58 Uhr
Fong, Peggy; Paul, Valerie J. (2011): Coral Reef Algae, in:  Dubinsky, Zwy and Stambler, Noga: Coral Reefs: An Ecosystem in Transition, Dordrecht, Heidelberg, London, New York, 241-272.
Hedley, John D.; Roelsema, Chris; Brando, Vittorio; Giardino, Claudia; Kutser, Tiit; Phinn, Stuart; Mumby, Peter J.; Barrilero, Omar; Laporte, Jean; Koetz, Benjamin (2018): Coral reef applications of Sentinel-2: Coverage, characteristics, bathymetry and benthic mapping with comparison to Landsat 8, Remote Sensing of Environment 216, 598-614.
Hoegh-Guldberg, O.; Mumby, P.J.; Hooten, A.J.; Steneck, R.S.; Greenfield, P.; Gomez, E. (2007): Coral reefs under rapid climate change and ocean acidification, in: Science 318, 1737-1742.
Hopley, David; Smithhers, Scott G.; Parnell, Kevin E. (2007): The Geomorphology of the Great Barrier Reef - Development, Diversity and Change, Cambridge, New York, Melbourne, Madrid, Cape Town, Singapore, Sâo Paulo.
Lesser, Micheal P. (2011): Coral Bleaching: Causes and Mechanisms, in: Dubinsky, Zwy and Stambler, Noga: Coral Reefs: An Ecosystem in Transition, Dordrecht, Heidelberg, London, New York, 405-419.
Liu, Gang und Strong, Alan E. (2003): Remote Sensing of Sea Surface Temperatures during 2002 Barrier Reef Coral Bleaching, EOS, Volume 84, Number 15.
Valueva, M.V.; Nagornov, N.N.; Lyakhov, P.A.; Valuev, G.V.; Charvyakov, N.I. (2020): Application of the residue number system to reduce hardware costs of the convolutional neural network implementation, in: Mathematics and Computers in Simulation 177, 232-243.
Weeks, Scarle J.; Berkelmans, Ray; Heron, Scott F. (2013): Thermal Applications, in: Goodman, James A.; Purkis, Samuel J.; Phinn, Stuart R.: Coral Reef Remote Sensing - A Guide for Mapping, Monitoring and Management, Dordrecht, Heidelberg, New York, London.
Xu, Jingping; Zhao, Jianhua; Wang, Fei; Chen, Yanlong und Lee, Zhongping (2021): Detection of Coral Reef Bleaching Based on Sentinel-2 Multi-Temporal Imagery: Simulation and Case Study, Frontiers in Marine Science March 2021, Volume 8.